### ISSUE TITLE
NullPointerException when Importing Items into Auto Workbench without Recipes

### ISSUE THREAD

**Issue by tonby** [mabidux/more-automation-mod#1]
Description:
When items are imported into an Auto Workbench from an external source (e.g., using a Hopper) without a set recipe, a NullPointerException occurs. The issue does not arise when a recipe is set before importing items.

Crash Report: https://pastebin.com/L90YLbPb

Versions:

    Minecraft: 1.20.1
    Forge: 47.2.0
    Mod: moreautomationmod-1.4.1.jar

**Comment by matheusabido** [comment]
Fixed. Thank you for reporting this issue!
